# Generated by Django 5.2.4 on 2025-07-10 10:51

from django.db import migrations, models
import django.db.models.deletion


def create_default_bot_and_update_tickets(apps, schema_editor):
    TelegramBot = apps.get_model('chatbot', 'TelegramBot')
    OpenTicket = apps.get_model('chatbot', 'OpenTicket')
    
    # Create default bot for existing tickets
    default_bot, created = TelegramBot.objects.get_or_create(
        name='Default Bot',
        defaults={'token': 'default_token_change_me'}
    )
    
    # Update existing tickets to use default bot
    OpenTicket.objects.filter(bot__isnull=True).update(bot=default_bot)


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_add_telegrambot'),
    ]

    operations = [
        # Add bot field to OpenTicket (nullable first)
        migrations.AddField(
            model_name='openticket',
            name='bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.telegrambot'),
        ),
        
        # Create default bot and assign to existing tickets
        migrations.RunPython(create_default_bot_and_update_tickets),
        
        # Make bot field non-nullable
        migrations.AlterField(
            model_name='openticket',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.telegrambot'),
        ),
        
        # Change telegram_id to not be primary key and remove unique constraint
        migrations.AlterField(
            model_name='openticket',
            name='telegram_id',
            field=models.BigIntegerField(),
        ),
        
        # Remove unique constraint on zammad_ticket_id
        migrations.AlterField(
            model_name='openticket',
            name='zammad_ticket_id',
            field=models.IntegerField(),
        ),
        
        # Add unique_together constraint
        migrations.AlterUniqueTogether(
            name='openticket',
            unique_together={('telegram_id', 'bot')},
        ),
    ]