# Generated by Django 5.2.4 on 2025-07-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_update_openticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='openticket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
