# Generated by Django 5.2.4 on 2025-07-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_openticket_id_telegrambot_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegrambot',
            old_name='group',
            new_name='zammad_group',
        ),
        migrations.AlterField(
            model_name='telegrambot',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
