# Generated by Django 5.2.4 on 2025-07-16 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='openticket',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chatbot.customer'),
        ),
    ]
