# Generated by Django 5.2.4 on 2025-07-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_openticket_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.IntegerField(),
        ),
    ]
