# Generated by Django 5.2.4 on 2025-07-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_remove_customer_last_name_alter_customer_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='customer_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='customer_prefix',
            field=models.CharField(blank=True, default='AZS', max_length=64, null=True),
        ),
    ]
