# Generated by Django 5.2.4 on 2025-07-23 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_telegrambot_customer_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZammadGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zammad_group', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('customer_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_prefix', models.CharField(blank=True, default='AZS', max_length=64, null=True)),
                ('telegram_bot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zammad_config', to='chatbot.telegrambot')),
            ],
        ),
    ]
