# Generated by Django 5.2.4 on 2025-07-23 07:21

from django.db import migrations


def migrate_telegram_bot_data(apps, schema_editor):
    """Copy data from TelegramBot fields to ZammadGroup model"""
    TelegramBot = apps.get_model('chatbot', 'TelegramBot')
    ZammadGroup = apps.get_model('chatbot', 'ZammadGroup')
    
    for bot in TelegramBot.objects.all():
        ZammadGroup.objects.create(
            telegram_bot=bot,
            zammad_group=bot.zammad_group,
            customer_last_name=bot.customer_last_name,
            customer_prefix=bot.customer_prefix or "AZS"
        )


def reverse_migrate_telegram_bot_data(apps, schema_editor):
    """Reverse migration - copy data back to TelegramBot fields"""
    TelegramBot = apps.get_model('chatbot', 'TelegramBot')
    ZammadGroup = apps.get_model('chatbot', 'ZammadGroup')
    
    for zammad_config in ZammadGroup.objects.all():
        bot = zammad_config.telegram_bot
        bot.zammad_group = zammad_config.zammad_group
        bot.customer_last_name = zammad_config.customer_last_name
        bot.customer_prefix = zammad_config.customer_prefix
        bot.save()


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_add_zammad_group_model'),
    ]

    operations = [
        migrations.RunPython(migrate_telegram_bot_data, reverse_migrate_telegram_bot_data),
    ]
