# Generated by Django 5.2.4 on 2025-07-23 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_migrate_telegram_bot_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrambot',
            name='customer_last_name',
        ),
        migrations.RemoveField(
            model_name='telegrambot',
            name='customer_prefix',
        ),
        migrations.RemoveField(
            model_name='telegrambot',
            name='zammad_group',
        ),
    ]
