# Generated by Django 5.2.4 on 2025-07-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_remove_old_telegram_bot_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zammadgroup',
            name='customer_prefix',
            field=models.CharField(default='AZS', max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('first_name', 'telegram_bot')},
        ),
    ]
