# Generated by Django 5.2.4 on 2025-07-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0013_unique_customer_per_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='openticket',
            name='priority',
            field=models.IntegerField(default=2),
        ),
    ]
