# Generated by Django 5.2.4 on 2025-07-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0015_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text Input'), ('choice', 'Multiple Choice'), ('photo', 'Photo Required')], default='text', max_length=10),
        ),
    ]
