# Generated by Django 5.2.4 on 2025-11-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0016_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='zammadgroup',
            name='preferable_language',
            field=models.CharField(choices=[('English', 'en'), ('Kyrgiz', 'ky'), ('Russian', 'ru')], default='ky', max_length=63),
        ),
    ]
