# Generated by Django 5.2.4 on 2025-11-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0017_zammadgroup_preferable_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zammadgroup',
            name='preferable_language',
            field=models.CharField(choices=[('en', 'English'), ('ky', 'Kyrgyz'), ('ru', 'Russian')], default='ky', max_length=63),
        ),
    ]
