# Generated by Django 5.2.4 on 2025-11-19 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0018_alter_zammadgroup_preferable_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ky', 'Кыргызча'), ('ru', 'Русский'), ('en', 'English')], max_length=2)),
                ('text', models.TextField(verbose_name='Question Text')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='chatbot.question')),
            ],
            options={
                'verbose_name': 'Question Translation',
                'verbose_name_plural': 'Question Translations',
                'unique_together': {('question', 'language')},
            },
        ),
    ]
